"""
NinjaTrader Parameter Exporter.

Exports optimized parameters to formats that can be used in NinjaTrader:
- JSON config file
- C# code block for direct copy/paste into Strategy Analyzer
- XML format for NinjaTrader import
"""

import json
from datetime import datetime
from typing import Dict, Any, Optional
from pathlib import Path


class NTParameterExporter:
    """
    Exports optimized parameters to NinjaTrader-compatible formats.

    Generates code/config that can be directly used in the NinjaTrader
    Strategy Analyzer or applied to the QQQIBBreakout strategy.
    """

    # Parameter name mapping from Python to NinjaTrader
    PARAM_MAPPING = {
        'ib_duration_minutes': 'IBDurationMinutes',
        'profit_target_percent': 'ProfitTargetPercent',
        'stop_loss_type': 'MyStopLossType',
        'ib_proximity_percent': 'IBProximityPercent',
        'trade_direction': 'MyTradeDirection',
        'fixed_share_size': 'FixedShareSize',
        'dollar_amount': 'DollarAmount',
        'trading_start_time': 'TradingStartTime',
        'trading_end_time': 'TradingEndTime',
        'use_qqq_filter': 'UseQQQFilter',
        'min_ib_range_percent': 'MinIBRangePercent',
        'max_ib_range_percent': 'MaxIBRangePercent',
        'max_breakout_time': 'MaxBreakoutTime',
        'trade_monday': 'TradeMonday',
        'trade_tuesday': 'TradeTuesday',
        'trade_wednesday': 'TradeWednesday',
        'trade_thursday': 'TradeThursday',
        'trade_friday': 'TradeFriday',
        'trailing_stop_enabled': 'TrailingStopEnabled',
        'trailing_stop_atr_mult': 'TrailingStopAtrMult',
        'break_even_enabled': 'BreakEvenEnabled',
        'break_even_pct': 'BreakEvenPct',
        'max_bars_enabled': 'MaxBarsEnabled',
        'max_bars': 'MaxBars',
        'eod_exit_time': 'EodExitTime',
    }

    # Value mapping for enums
    STOP_LOSS_TYPE_MAP = {
        'opposite_ib': 'StopLossType.OppositeIB',
        'match_target': 'StopLossType.MatchTarget',
    }

    TRADE_DIRECTION_MAP = {
        'both': 'TradeDirection.Both',
        'long_only': 'TradeDirection.LongOnly',
        'short_only': 'TradeDirection.ShortOnly',
    }

    def __init__(self, output_dir: Optional[str] = None):
        """
        Initialize exporter.

        Args:
            output_dir: Directory for output files
        """
        self.output_dir = Path(output_dir) if output_dir else Path.cwd() / "nt_export"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export_to_json(
        self,
        params: Dict[str, Any],
        filename: str = "optimal_params.json",
        metadata: Optional[Dict] = None
    ) -> str:
        """
        Export parameters to JSON file.

        Args:
            params: Optimized parameters
            filename: Output filename
            metadata: Optional metadata (backtest results, etc.)

        Returns:
            Path to saved file
        """
        export_data = {
            'generated_at': datetime.now().isoformat(),
            'source': 'IB Breakout Optimizer',
            'parameters': params,
        }

        if metadata:
            export_data['metadata'] = metadata

        filepath = self.output_dir / filename
        with open(filepath, 'w') as f:
            json.dump(export_data, f, indent=2)

        print(f"Parameters exported to: {filepath}")
        return str(filepath)

    def export_to_csharp(
        self,
        params: Dict[str, Any],
        filename: str = "optimal_params.cs"
    ) -> str:
        """
        Export parameters as C# code block.

        This generates code that can be pasted directly into the
        NinjaTrader Strategy properties panel or used as a reference.

        Args:
            params: Optimized parameters
            filename: Output filename

        Returns:
            Path to saved file
        """
        lines = [
            "// ============================================================",
            "// OPTIMAL PARAMETERS - Generated by IB Breakout Optimizer",
            f"// Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "// ============================================================",
            "",
            "// Copy these values into NinjaTrader Strategy Analyzer",
            "// or apply them in the Strategy Properties panel",
            "",
            "// IB Parameters",
        ]

        # IB Duration
        if 'ib_duration_minutes' in params:
            lines.append(f"IBDurationMinutes = {params['ib_duration_minutes']};")

        # Profit Target
        if 'profit_target_percent' in params:
            lines.append(f"ProfitTargetPercent = {params['profit_target_percent']};")

        # Stop Loss Type
        if 'stop_loss_type' in params:
            nt_value = self.STOP_LOSS_TYPE_MAP.get(params['stop_loss_type'], 'StopLossType.OppositeIB')
            lines.append(f"MyStopLossType = {nt_value};")

        # IB Proximity
        if 'ib_proximity_percent' in params:
            lines.append(f"IBProximityPercent = {params['ib_proximity_percent']};")

        # Trade Direction
        if 'trade_direction' in params:
            nt_value = self.TRADE_DIRECTION_MAP.get(params['trade_direction'], 'TradeDirection.Both')
            lines.append(f"MyTradeDirection = {nt_value};")

        lines.append("")
        lines.append("// Position Sizing")

        # Position Sizing
        if 'fixed_share_size' in params:
            lines.append(f"FixedShareSize = {params['fixed_share_size']};")
        if 'dollar_amount' in params:
            lines.append(f"DollarAmount = {params['dollar_amount']};")

        lines.append("")
        lines.append("// Trading Hours")

        # Trading Times
        if 'trading_start_time' in params:
            time_str = params['trading_start_time']
            lines.append(f'TradingStartTime = DateTime.Parse("{time_str}", System.Globalization.CultureInfo.InvariantCulture);')
        if 'trading_end_time' in params:
            time_str = params['trading_end_time']
            lines.append(f'TradingEndTime = DateTime.Parse("{time_str}", System.Globalization.CultureInfo.InvariantCulture);')

        lines.append("")
        lines.append("// Filters")

        # Filters
        if 'use_qqq_filter' in params:
            lines.append(f"UseQQQFilter = {str(params['use_qqq_filter']).lower()};")
        if 'min_ib_range_percent' in params:
            lines.append(f"MinIBRangePercent = {params['min_ib_range_percent']};")
        if 'max_ib_range_percent' in params:
            lines.append(f"MaxIBRangePercent = {params['max_ib_range_percent']};")
        if 'max_breakout_time' in params:
            time_str = params['max_breakout_time']
            lines.append(f'MaxBreakoutTime = DateTime.Parse("{time_str}", System.Globalization.CultureInfo.InvariantCulture);')

        # Day of week filters
        lines.append("")
        lines.append("// Day of Week Filters")
        for day in ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']:
            key = f'trade_{day}'
            if key in params:
                nt_key = f"Trade{day.capitalize()}"
                lines.append(f"{nt_key} = {str(params[key]).lower()};")

        # Advanced exits (if present)
        if any(k in params for k in ['trailing_stop_enabled', 'break_even_enabled', 'max_bars_enabled']):
            lines.append("")
            lines.append("// Advanced Exit Parameters")

            if params.get('trailing_stop_enabled'):
                lines.append(f"// TrailingStopEnabled = {str(params['trailing_stop_enabled']).lower()};")
                if 'trailing_stop_atr_mult' in params:
                    lines.append(f"// TrailingStopAtrMult = {params['trailing_stop_atr_mult']};")

            if params.get('break_even_enabled'):
                lines.append(f"// BreakEvenEnabled = {str(params['break_even_enabled']).lower()};")
                if 'break_even_pct' in params:
                    lines.append(f"// BreakEvenPct = {params['break_even_pct']};")

            if params.get('max_bars_enabled'):
                lines.append(f"// MaxBarsEnabled = {str(params['max_bars_enabled']).lower()};")
                if 'max_bars' in params:
                    lines.append(f"// MaxBars = {params['max_bars']};")

        lines.append("")
        lines.append("// ============================================================")

        content = "\n".join(lines)

        filepath = self.output_dir / filename
        with open(filepath, 'w') as f:
            f.write(content)

        print(f"C# code exported to: {filepath}")
        return str(filepath)

    def export_summary(
        self,
        params: Dict[str, Any],
        metrics: Dict[str, Any],
        filename: str = "optimization_summary.txt"
    ) -> str:
        """
        Export a human-readable summary with parameters and metrics.

        Args:
            params: Optimized parameters
            metrics: Performance metrics
            filename: Output filename

        Returns:
            Path to saved file
        """
        lines = [
            "=" * 60,
            "IB BREAKOUT STRATEGY - OPTIMIZATION RESULTS",
            "=" * 60,
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "OPTIMAL PARAMETERS:",
            "-" * 40,
        ]

        # Format parameters
        for key, value in sorted(params.items()):
            lines.append(f"  {key}: {value}")

        if metrics:
            lines.extend([
                "",
                "BACKTEST RESULTS:",
                "-" * 40,
            ])
            for key, value in sorted(metrics.items()):
                if isinstance(value, float):
                    lines.append(f"  {key}: {value:.4f}")
                else:
                    lines.append(f"  {key}: {value}")

        lines.extend([
            "",
            "=" * 60,
            "TO APPLY IN NINJATRADER:",
            "=" * 60,
            "",
            "1. Open NinjaTrader Strategy Analyzer",
            "2. Load QQQIBBreakout strategy",
            "3. In the Parameters section, update values as shown above",
            "4. Run backtest to verify performance matches",
            "",
            "Note: Some parameters may not be present in your version",
            "of QQQIBBreakout.cs. Skip those parameters or add them",
            "to the strategy code if needed.",
            "",
            "=" * 60,
        ])

        content = "\n".join(lines)

        filepath = self.output_dir / filename
        with open(filepath, 'w') as f:
            f.write(content)

        print(f"Summary exported to: {filepath}")
        return str(filepath)

    def print_parameters(self, params: Dict[str, Any]):
        """Print parameters in a formatted table."""
        print("\n" + "=" * 60)
        print("OPTIMAL PARAMETERS FOR NINJATRADER")
        print("=" * 60)

        # Core parameters
        print("\nCore Parameters:")
        print("-" * 40)
        print(f"  IB Duration:        {params.get('ib_duration_minutes', 30)} minutes")
        print(f"  Profit Target:      {params.get('profit_target_percent', 0.5)}%")
        print(f"  Stop Loss:          {params.get('stop_loss_type', 'opposite_ib')}")
        print(f"  Trade Direction:    {params.get('trade_direction', 'both')}")

        # Filters
        print("\nFilters:")
        print("-" * 40)
        print(f"  QQQ Filter:         {'ON' if params.get('use_qqq_filter', False) else 'OFF'}")
        print(f"  Min IB Range:       {params.get('min_ib_range_percent', 0.0)}%")
        print(f"  Max IB Range:       {params.get('max_ib_range_percent', 10.0)}%")
        print(f"  Max Breakout Time:  {params.get('max_breakout_time', '14:00')}")

        # Trading window
        print("\nTrading Window:")
        print("-" * 40)
        print(f"  Start:              {params.get('trading_start_time', '09:00')}")
        print(f"  End:                {params.get('trading_end_time', '15:00')}")

        print("\n" + "=" * 60)


def export_optimization_results(
    params: Dict[str, Any],
    metrics: Optional[Dict[str, Any]] = None,
    output_dir: str = None,
    ticker: str = "unknown"
) -> Dict[str, str]:
    """
    Convenience function to export all formats at once.

    Args:
        params: Optimized parameters
        metrics: Performance metrics (optional)
        output_dir: Output directory
        ticker: Ticker symbol for filenames

    Returns:
        Dict mapping format -> filepath
    """
    exporter = NTParameterExporter(output_dir)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = f"{ticker}_{timestamp}"

    files = {}

    # JSON
    files['json'] = exporter.export_to_json(
        params,
        f"{base_name}_params.json",
        metrics
    )

    # C#
    files['csharp'] = exporter.export_to_csharp(
        params,
        f"{base_name}_params.cs"
    )

    # Summary
    if metrics:
        files['summary'] = exporter.export_summary(
            params,
            metrics,
            f"{base_name}_summary.txt"
        )

    # Print to console
    exporter.print_parameters(params)

    return files


if __name__ == "__main__":
    # Test with sample parameters
    test_params = {
        'ib_duration_minutes': 30,
        'profit_target_percent': 0.5,
        'stop_loss_type': 'opposite_ib',
        'ib_proximity_percent': 0,
        'trade_direction': 'long_only',
        'fixed_share_size': 100,
        'dollar_amount': 0,
        'trading_start_time': '09:00',
        'trading_end_time': '15:00',
        'use_qqq_filter': False,
        'min_ib_range_percent': 0.0,
        'max_ib_range_percent': 10.0,
        'max_breakout_time': '14:00',
        'trade_monday': True,
        'trade_tuesday': True,
        'trade_wednesday': True,
        'trade_thursday': True,
        'trade_friday': True,
    }

    test_metrics = {
        'total_trades': 159,
        'win_rate': 57.5,
        'total_pnl': 5101.71,
        'profit_factor': 1.58,
        'sharpe_ratio': 3.14,
        'max_drawdown': 953.69,
    }

    files = export_optimization_results(
        test_params,
        test_metrics,
        output_dir=r"C:\Users\Warren\Projects\ib_breakout_optimizer\output\nt_export",
        ticker="QQQ"
    )

    print("\n\nExported files:")
    for fmt, path in files.items():
        print(f"  {fmt}: {path}")
